# Generated by Django 3.2 on 2021-04-26 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 3, 48, 45, 410465)),
        ),
    ]
