# Generated by Django 3.2 on 2021-04-25 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='debut_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
